# GitHub Actions Workflow for ARI Automation Web App

name: ARI Web App Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./webapp
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Azure Login
      uses: azure/login@v1
      if: ${{ success() && github.event_name != 'pull_request' && secrets.AZURE_CREDENTIALS != '' }}
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      if: ${{ success() && github.event_name != 'pull_request' && secrets.AZURE_CREDENTIALS != '' }}
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        images: 'ghcr.io/${{ github.repository }}:${{ github.sha }}'
        
    - name: Deploy to Azure Container Apps
      if: ${{ success() && github.event_name != 'pull_request' && secrets.AZURE_CREDENTIALS != '' && secrets.AZURE_CONTAINERAPP_NAME != '' }}
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az extension add --name containerapp --upgrade
          az containerapp update \
            --name ${{ secrets.AZURE_CONTAINERAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ghcr.io/${{ github.repository }}:${{ github.sha }}
