name: Azure Web App Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Set up PowerShell
        uses: actions/setup-powershell@v1
        with:
          powershell-version: '7.2'
          
      - name: Install Azure PowerShell module
        run: |
          pwsh -Command "Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser"
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Build and Deploy Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./webapp
          
      - name: Configure Web App
        run: |
          pwsh -Command "Import-Module Az.Websites; Set-AzWebApp -Name ${{ secrets.AZURE_WEBAPP_NAME }} -ResourceGroupName ${{ secrets.AZURE_RESOURCE_GROUP }} -AppSettings @{'ARI_EXECUTION_TIMEOUT'='3600'; 'AZURE_TENANT_ID'='${{ secrets.AZURE_TENANT_ID }}'; 'AZURE_SUBSCRIPTION_ID'='${{ secrets.AZURE_SUBSCRIPTION_ID }}'}"
